import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import Footer from './components/compounds/footer';
import Header from './components/compounds/header';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <main className="w-full">
          <Header />
            {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
